### ISSUE TITLE
iF.SVNAdmin的代码仓库浏览页面报错warning: W000013: Can't open file '/root/.subversion/servers'

### ISSUE THREAD

**Issue by zhanghw0917** [li-franky/docker-svnserver#1]
你好，
使用提供的镜像 搭建完成后，在使用iF.SVNAdmin的代码仓库浏览功能时页面顶部报错:
 (/usr/bin/svn error=svn: warning: W000013: Can't open file '/root/.subversion/servers': Permission denied
)
"/usr/bin/svn" ls --xml --non-interactive --trust-server-cert file:///var/www/html/data/repositories/test/

需要点击进入创建的代码仓库中，如test中 ，或任意一级目录都会报错

**Comment by li-franky** [comment]
svn服务是通过容器中的apache用户启动的，所以需要让容器内的服务有读写映射到容器的文件夹的权限。
就拿README文件中的启动命令来说：
```
docker run -d --name svnserver \
--volume /opt/svn_repo:/var/www/html/data \
--publish 80:80 \
frankylee/websvn:0.1
```
容器中的apache用户的id是48，容器映射到宿主机的id一样是48。宿主机被映射的路径是/opt/svn_repo，所以执行如下命令：
```
sudo chown -R 48:48 /opt/svn_repo
```
然后再启动容器试一下。

**Comment by zhanghw0917** [comment]
感谢回复； 
我检查过了，宿主机中的svn_repo目录 就是48的用户所有的，
然后我把目前权限修改为了 777，重启或删除镜像重启 都尝试过了
再试，仍是以上问题

drwxrwxrwx 4   48   48 4096 Jan 18 20:53 svn_repo

错误截图如下 ：

<img width="928" alt="wx20190121-202947 2x" src="https://user-images.githubusercontent.com/4417233/51474835-7aedb780-1dbb-11e9-93ac-92edd90a6645.png">



ps：
我用的是以下 命令运行的，用的0.2版本
docker run -d --name svnserver \
	--volume /home/svn_repo:/var/www/html/data \
	--publish 18080:80 \
	frankylee/websvn:0.2

**Comment by zhanghw0917** [comment]
问题解决了 ；
方式是将apache 用户添加到root 组里面
usermod -a -G root apache

估计是要重启，但是在里面重启 发现httpd -k restart 不好使
所以在外面重启的容器 docker restart 容器ID
然后刷新网页 就ok了

希望可以把这点添加进去 ，重新打包，谢谢
